import { Layout } from "@/components/Layout";
import { SEO } from "@/components/SEO";
import { Card } from "@/components/ui/card";
import { AlertTriangle } from "lucide-react";

export default function Disclaimer() {
  return (
    <Layout>
      <SEO
        title="Investment Disclaimer - Bloom"
        description="Investment Disclaimer for Bloom by Cinder Vault Enterprises LLC"
      />
      <div className="mx-auto max-w-4xl space-y-8 px-4 py-8">
        <div>
          <h1 className="mb-2 font-serif text-4xl font-bold text-primary">Investment Disclaimer</h1>
          <p className="text-muted-foreground">Cinder Vault Enterprises LLC</p>
        </div>

        <Card className="border-destructive bg-destructive/5 p-6">
          <div className="flex items-start gap-4">
            <AlertTriangle className="h-6 w-6 shrink-0 text-destructive" />
            <div>
              <h2 className="mb-2 font-serif text-xl font-semibold text-destructive">IMPORTANT - PLEASE READ CAREFULLY</h2>
              <p className="text-sm text-foreground">
                The following disclaimer contains critical information about the limitations of Bloom's services. By using Bloom, you acknowledge that you have read and understood this disclaimer.
              </p>
            </div>
          </div>
        </Card>

        <Card className="p-6">
          <div className="prose prose-sm max-w-none">
            <h2 className="mb-4 font-serif text-2xl font-semibold text-primary">Not Financial Advice</h2>
            <p className="mb-2 text-foreground">
              Bloom and all content provided by Pansy, our AI guide, is strictly for educational and informational purposes.
            </p>
            <p className="mb-2 text-foreground">Nothing on this platform should be interpreted as:</p>
            <ul className="mb-6 space-y-2 text-foreground">
              <li>Financial or investment advice</li>
              <li>A recommendation to buy or sell any security</li>
              <li>An endorsement of any particular investment strategy</li>
              <li>A guarantee of any investment outcome</li>
            </ul>

            <h2 className="mb-4 font-serif text-2xl font-semibold text-primary">No Registered Status</h2>
            <p className="mb-2 text-foreground">Cinder Vault Enterprises LLC and Bloom are NOT:</p>
            <ul className="mb-6 space-y-2 text-foreground">
              <li>Registered investment advisors</li>
              <li>Licensed broker-dealers</li>
              <li>Financial planners or consultants</li>
              <li>Affiliated with any regulatory body</li>
            </ul>

            <h2 className="mb-4 font-serif text-2xl font-semibold text-primary">Risk Disclosure</h2>
            <p className="mb-6 text-foreground">
              All investing involves significant risk, including the possible loss of principal. Past performance of any security, ETF, stock, or investment strategy does not guarantee future results. Market conditions change rapidly and unpredictably. You should never invest money you cannot afford to lose.
            </p>

            <h2 className="mb-4 font-serif text-2xl font-semibold text-primary">AI Analysis Disclosure</h2>
            <p className="mb-6 text-foreground">
              Pansy's analysis is generated by artificial intelligence and is based on publicly available market data. AI analysis may be incomplete, inaccurate, or outdated. Always verify information independently before making any investment decision. Cinder Vault Enterprises LLC is not responsible for any losses resulting from reliance on AI-generated content.
            </p>

            <h2 className="mb-4 font-serif text-2xl font-semibold text-primary">Broker Affiliate Disclosure</h2>
            <p className="mb-6 text-foreground">
              Some broker recommendations on Bloom are part of affiliate partnerships. Cinder Vault Enterprises LLC may earn a referral fee when users sign up with recommended brokers. Affiliate relationships do not influence the educational content or analysis provided by Bloom. We only recommend brokers we genuinely believe provide value to our users.
            </p>

            <h2 className="mb-4 font-serif text-2xl font-semibold text-primary">Consult a Professional</h2>
            <p className="mb-6 text-foreground">
              Before making any investment decisions, we strongly encourage you to consult with a qualified financial advisor who understands your personal financial situation, goals, and risk tolerance.
            </p>

            <h2 className="mb-4 font-serif text-2xl font-semibold text-primary">Contact</h2>
            <p className="text-foreground">
              For questions about this disclaimer, contact:<br />
              <a href="mailto:cindervaultenterprisesllc@gmail.com" className="text-primary hover:underline">cindervaultenterprisesllc@gmail.com</a><br />
              Cinder Vault Enterprises LLC<br />
              <a href="https://shebloomswealth.app" className="text-primary hover:underline">shebloomswealth.app</a>
            </p>
          </div>
        </Card>

        <Card className="border-accent bg-accent/5 p-4">
          <p className="text-sm text-muted-foreground">
            This is educational content only and does not constitute financial advice. Bloom is not liable for any investment decisions or losses.
          </p>
        </Card>
      </div>
    </Layout>
  );
}